# <b>Student Performance Application</b>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv("/content/Student_Performance.csv")
df.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0

### 1. Read the data and perform basic EDA

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Hours Studied                     10000 non-null  int64
 1   Previous Scores                   10000 non-null  int64
 2   Extracurricular Activities        10000 non-null  object
 3   Sleep Hours                       10000 non-null  int64
 4   Sample Question Papers Practiced  10000 non-null  int64
 5   Performance Index                 10000 non-null  float64
dtypes: float64(1), int64(4), object(1)
memory usage: 468.9+ KB

In [ ]:
df.isna().sum()

Hours Studied                       0
Previous Scores                     0
Extracurricular Activities          0
Sleep Hours                         0
Sample Question Papers Practiced    0
Performance Index                   0
dtype: int64

### 2. Prepare the data for the Modelling

In [ ]:
df["Extracurricular Activities"] = df["Extracurricular Activities"].replace({"Yes":1, "No":0})

/tmp/ipython-input-4153357838.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["Extracurricular Activities"] = df["Extracurricular Activities"].replace({"Yes":1, "No":0})

In [ ]:
df.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,1,9,1,91.0
1,4,82,0,4,2,65.0
2,8,51,1,7,2,45.0
3,5,52,1,5,2,36.0
4,7,75,0,8,5,66.0

In [ ]:
x = df.drop("Performance Index", axis=1)
x.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced
0,7,99,1,9,1
1,4,82,0,4,2
2,8,51,1,7,2
3,5,52,1,5,2
4,7,75,0,8,5

In [ ]:
y = df["Performance Index"]
y.head()

0    91.0
1    65.0
2    45.0
3    36.0
4    66.0
Name: Performance Index, dtype: float64

#### Splitting the Dataset into train and test data

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42)

In [ ]:
x_train.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced
4901,5,49,0,5,5
4375,7,88,1,4,9
6698,3,94,1,7,1
9805,9,54,1,5,9
1101,4,56,1,8,6

In [ ]:
y_train.head()

4901    33.0
4375    82.0
6698    74.0
9805    49.0
1101    43.0
Name: Performance Index, dtype: float64

In [ ]:
x_test.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced
6252,5,69,0,8,2
4684,2,46,1,4,8
1731,7,56,1,7,5
4742,6,42,1,8,5
4521,7,53,0,4,6

In [ ]:
y_test.head()

6252    51.0
4684    20.0
1731    46.0
4742    28.0
4521    41.0
Name: Performance Index, dtype: float64

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
Scaler = StandardScaler()
Scaled_train = Scaler.fit_transform(x_train)
Scaled_train

array([[ 0.00796272, -1.19062085, -0.98912579, -0.90874945,  0.13314392],
       [ 0.77854894,  1.05902612,  1.01099376, -1.49731775,  1.53122497],
       [-0.76262349,  1.40512565,  1.01099376,  0.26838714, -1.26493713],
       ...,
       [ 1.54913515, -1.24830411, -0.98912579,  0.26838714,  0.48266418],
       [-1.5332097 , -1.30598737, -0.98912579,  1.44552374, -1.6144574 ],
       [-1.14791659, -1.36367062, -0.98912579, -0.32018115,  0.48266418]])

In [ ]:
Scaled_test = Scaler.transform(x_test)
Scaled_test

array([[ 0.00796272, -0.03695574, -0.98912579,  0.85695544, -0.91541687],
       [-1.14791659, -1.36367062,  1.01099376, -1.49731775,  1.18170471],
       [ 0.77854894, -0.78683806,  1.01099376,  0.26838714,  0.13314392],
       ...,
       [ 0.00796272,  0.65524333, -0.98912579,  0.85695544,  1.18170471],
       [-0.37733038,  0.13609403, -0.98912579, -0.90874945, -0.56589661],
       [ 1.16384204, -0.44073853,  1.01099376, -1.49731775, -0.91541687]])

In [ ]:
x_train[x_train.columns] = Scaled_train

In [ ]:
x_train.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced
4901,0.007963,-1.190621,-0.989126,-0.908749,0.133144
4375,0.778549,1.059026,1.010994,-1.497318,1.531225
6698,-0.762623,1.405126,1.010994,0.268387,-1.264937
9805,1.549135,-0.902205,1.010994,-0.908749,1.531225
1101,-0.377330,-0.786838,1.010994,0.856955,0.482664

In [ ]:
x_test[x_test.columns] = Scaled_test
x_test.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced
6252,0.007963,-0.036956,-0.989126,0.856955,-0.915417
4684,-1.147917,-1.363671,1.010994,-1.497318,1.181705
1731,0.778549,-0.786838,1.010994,0.268387,0.133144
4742,0.393256,-1.594404,1.010994,0.856955,0.133144
4521,0.778549,-0.959888,-0.989126,-1.497318,0.482664

In [ ]:
joblib.dump(Scaler, "scaler.joblib")

['scaler.joblib']

### 3. Train a Linear Regression model

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
model = LinearRegression()

In [ ]:
model.fit(x_train, y_train)

LinearRegression()

### 4. Test the model using the new (unseen) data

In [ ]:
y_pred = model.predict(x_test)
y_pred

array([54.73187888, 22.61211054, 47.90838844, ..., 68.07396952,
       53.68636805, 54.85816372])

In [ ]:
y_test

6252    51.0
4684    20.0
1731    46.0
4742    28.0
4521    41.0
        ...
4862    83.0
7025    31.0
7647    70.0
7161    56.0
73      52.0
Name: Performance Index, Length: 2500, dtype: float64

### R<sup>2</sup> Score

In [ ]:
train_r2 = model.score(x_train, y_train)
round(train_r2*100,2)

98.86

In [ ]:
test_r2 = model.score(x_test, y_test)
round(test_r2*100,2)

98.91

### 5. Save the model using joblib

In [ ]:
import joblib

In [ ]:
import joblib

# Save the model
joblib.dump(model, "Student_performance_model.joblib")

['Student_performance_model.joblib']